### ISSUE TITLE
Enable saving tabs for a single project

### ISSUE THREAD

**Issue by ittaiz** [alp82/idea-tabsession#1]
Hi,
First of all thanks for a great plugin. It seems to be exactly what I needed.
The only drawback is that I usually work with several projects open and when I use the plugin it saves the status of all of them.
Any chance to add a checkbox to choose whether or not to save the current project or all of them?

**Comment by alp82** [comment]
Hello ittaiz, that's a great suggestion. I'm currently working on support for splitted windows. After that i'd be happy to implement proper handling for multiple instances of open projects.

**Comment by ittaiz** [comment]
Thanks!

**Comment by alp82** [comment]
This project will not be continued because IDEA already supports that feature. You can save and load contexts easily as shown in this screenshot:

![IDEA Context](http://ibin.co/1yLedwskhh2f)
