### ISSUE TITLE
Add support for PyCharm

### ISSUE THREAD

**Issue by jwien001** [alp82/idea-tabsession#5]
Hi,
I've been using this plugin in IDEA for quite awhile now, and I love it! However, I recently started using PyCharm and was sad to find out that Tab Session is not compatible. Any chance you could add support for PyCharm?

**Comment by alp82** [comment]
Thanks for the kind words. I do not have PyCharm, but i could try to make it compatible. The other issues have higher priority though and i am currently in a quite big refactoring phase of the project. Do not expect support anytime soon.

**Comment by jwien001** [comment]
Ok, thanks for considering it. I'm excited by the other features as well,
so I'll be happy either way.

**Comment by alp82** [comment]
This project will not be continued because IDEA already supports that feature. You can save and load contexts easily as shown in this screenshot:

![IDEA Context](http://ibin.co/1yLedwskhh2f)
