### ISSUE TITLE
Support for version PhpStorm 8

### ISSUE THREAD

**Issue by bentcoder** [alp82/idea-tabsession#6]
Hi,

I guess it is not supported by version 8.0.3 because I cannot see any option as described in order to handle sessions. Will it be updated?

Thanks

![screenshot from 2015-04-14 11 05 48](https://cloud.githubusercontent.com/assets/8837278/7134636/979177a0-e296-11e4-8849-d8769a642e49.png)

**Comment by alp82** [comment]
This project will not be continued because IDEA already supports that feature. You can save and load contexts easily as shown in this screenshot:

![IDEA Context](http://ibin.co/1yLedwskhh2f)
